### ISSUE TITLE
Support for Angular 10

### ISSUE THREAD

**Issue by TokkeDev** [IceBreakerG/ngx-version-check#7]
ngx-version-check should allow peer dependency of Angular 10. When doing npm install, the following errors appear:
```
npm WARN ngx-version-check@1.0.1 requires a peer of @angular/common@^8.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-version-check@1.0.1 requires a peer of @angular/core@^8.2.4 but none is installed. You must install peer dependencies yourself.
```

However, everything works fine with both Angular 9 and Angular 10, so I think the peer dependencies of ngx-version-check should be updated to also accept Angular 10

**Comment by IceBreakerG** [comment]
@TokkeDev The peer dependencies are showing the minimum supported version, even though it will work correctly with other versions. The problem is that if I change the peer dependency to support Angular 10, you will get a warning when you upgrade to Angular 11. I think the only solution to eliminating the warning would be to remove the peer dependency altogether.

**Comment by TokkeDev** [comment]
I don't agree with you all the way there. It's awesome that it just works with Angular 9 and 10, but when there is a major Angular version bump, it should be tested that everything still works (as the update might have broken something in ngx-version-check). So in my opinion, the peer dependency should definitely remain, and then whenever there's a major version release, ngx-version-check should be tested to still work and then the version of the peer dependency should be bumped. After all, major releases only occur about every 6 months [according to Angular](https://angular.io/guide/releases#release-frequency). 
I'd be happy to help out!

**Comment by IceBreakerG** [comment]
@TokkeDev Sorry about the delay in response. I understand what you're saying. I didn't fully understand how the peerDependencies could be set in the package.json file, but I read earlier today that I can use `>=` to specify the compatible versions as well. I'll be updating the package sometime in the next few days with these changes, so those warnings should go away when you do an install. I'm still testing some things with it.

**Comment by TokkeDev** [comment]
No worries. That sounds good. I’m looking forward to the update 😊

**Comment by IceBreakerG** [comment]
@TokkeDev I just published the updated version. There aren't really any functionality changes, just minor maintenance stuff, and it should fix the issue you were having with the dependencies showing the warnings for the angular versions. Let me know if you find anything else. Thanks for your patience.

**Comment by TokkeDev** [comment]
Very nice, it's working perfectly 🙏😊

**Comment by IceBreakerG** [comment]
Good to hear. Thank you!
